
FIND_PATH(EINSPLINE_INCLUDE_DIR
  NAMES einspline/bspline.h
  PATHS ${EINSPLINE_DIR}/include/
  NO_DEFAULT_PATH
  )

FIND_PATH(EINSPLINE_INCLUDE_DIR
  NAMES einspline/bspline.h
  PATHS ${EINSPLINE_DIR}/include/
  DOC "The Einspline include directory")

FIND_LIBRARY(EINSPLINE_LIBRARY
  NAMES einspline
  PATHS ${EINSPLINE_DIR}/lib/
  NO_DEFAULT_PATH)

FIND_LIBRARY(EINSPLINE_LIBRARY
  NAMES einspline
  PATHS ${EINSPLINE_DIR}/lib/ ${EINSPLINE_LIBRARY_DIR}
  DOC "The Einspline LIBRARY directory")

GET_FILENAME_COMPONENT(EINSPLINE_LIBRARY_DIR ${EINSPLINE_LIBRARY} PATH)

SET(EINSPLINE_LIBRARIES ${EINSPLINE_LIBRARY})
SET(EINSPLINE_INCLUDE_DIRS ${EINSPLINE_INCLUDE_DIR})

IF(EINSPLINE_INCLUDE_DIR)
  INCLUDE(FindPackageHandleStandardArgs)
  FIND_PACKAGE_HANDLE_STANDARD_ARGS(Einspline
    REQUIRED_VARS EINSPLINE_LIBRARY
    EINSPLINE_INCLUDE_DIR
    VERSION_VAR EINSPLINE_VERSION_STRING)
ENDIF()

MARK_AS_ADVANCED(EINSPLINE_INCLUDE_DIR EINSPLINE_LIBRARY)
